### ISSUE TITLE
Toggling IO Mapping in default rendering template component, breaks the component

### ISSUE THREAD

**Issue by MaxTru** [bpmn-io/bpmn-properties-panel#186]
__Describe the Bug__

Toggling IO Mapping in default rendering template component, breaks the component

__Steps to Reproduce__

1. Have template with default rendering for IO Mapping
2. Remove all IO Mappings
3. Add IO Mappings
=> IO Mapping is now broken

![Peek 2021-11-18 17-07](https://user-images.githubusercontent.com/42800119/142495925-0fc09880-c67e-4398-9538-7c635d57d5a5.gif)

__Expected Behavior__

IO Mapping does not break

__Environment__

https://github.com/bpmn-io/bpmn-properties-panel/pull/161

**Comment by barmac** [comment]
So the problem here is that we create an empty `camunda:InputOutput` as one of the steps in the multi-command. This is cleaned up in between via https://github.com/camunda/camunda-bpmn-js/blob/main/lib/camunda-platform/features/modeling/behavior/UpdateInputOutputBehavior.js

I think the way to go is to stop using multi-command and add `camunda:InputOutput` with the content inside via one command.
