### ISSUE TITLE
Implement inputs & outputs group

### ISSUE THREAD

**Issue by barmac** [bpmn-io/bpmn-properties-panel#54]
This requires nested lists concept.

Cf. the [prototype](https://fluffy-fiesta-212e1c7c.pages.github.io/prototypes/visual-ide/v14/).

### Inputs

* String or expression
![image](https://user-images.githubusercontent.com/9433996/131982993-91fb8bb1-1166-47f9-a02f-18a4236998a2.png)

* <del>To be discussed: do we want to rebuild the custom auto complete component or wait for a proper code editor component?</del> ==> no, cf. https://github.com/bpmn-io/bpmn-properties-panel/issues/54#issuecomment-913479908
![image](https://user-images.githubusercontent.com/9433996/131983347-6c9bcff2-b608-435b-84cb-54789b41badb.png)

* Script
![image](https://user-images.githubusercontent.com/9433996/131983150-4f03ef94-573d-4085-bc32-73b0d04fc169.png)

* List
![image](https://user-images.githubusercontent.com/9433996/131983214-d0a86336-0661-49b3-83ec-cc1388c6a15f.png)

* Map
![image](https://user-images.githubusercontent.com/9433996/131983254-768f33ff-b1f9-4b2e-a99a-55e3ca483a08.png)

<hr></hr>

### Outputs

* String or expression
![image](https://user-images.githubusercontent.com/9433996/131983730-40480e13-c9e7-481a-8efd-704f2e0b7ef9.png)

* Script
![image](https://user-images.githubusercontent.com/9433996/131983800-deeeb7ed-c5e0-4a17-bce4-608a54e1c9e8.png)

* List
![image](https://user-images.githubusercontent.com/9433996/131983834-fc1f129b-475b-4d95-903d-977edf6f7da8.png)

* Map
![image](https://user-images.githubusercontent.com/9433996/131983861-76f65279-7223-4f17-b4bb-ec292a787b20.png)

**Comment by pinussilvestrus** [comment]
> In case of camunda:inputOutput, only the first syntax error in an expression is reported by the engine; XML order matter

Source: https://github.com/bpmn-io/bpmn-properties-panel/issues/2#issuecomment-912586928

Therefore we might consider disabling sorting here.

**Comment by pinussilvestrus** [comment]
Inside the old properties panel, we created a first iteration of what we call "auto-suggest text component" - only used by input/output parameter expressions. The question for me would be whether we want to spend time rebuilding this thing. I'd vote for **no** and tackle it at a later point in time because

* it was really just a first iteration and there is much room for improvement
* it would take us time to build this "hack" again
* it would take us more time right now to build a proper autocomplete (concept + implementation)
* we plan to maybe have a proper code editor/syntax highlighting component anyway in the future (at least we had it once in our OKRs)
* we don't know yet how much this single input was actually used

![image](https://user-images.githubusercontent.com/9433996/132190140-06d60de5-f236-4ebb-82fe-5dbf2d094d5f.png)
